old_sound_rabbit_mq:
    connections:
        default:
            #host:     '%env(string:RABBITMQ_HOST)%'
            #port:     '%env(string:RABBITMQ_PORT)%'
            #user:     '%env(string:RABBITMQ_USER)%'
            #password: '%env(string:RABBITMQ_PASSWORD)%'
            #vhost:    '%env(string:RABBITMQ_VHOST)%'
            #lazy:     true
            #connection_timeout: 3
            #read_write_timeout: 3
            url: '%env(RABBITMQ_VHOST_AMQP_URL)%'

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: true

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            #url: ''
    producers:
        sum_values:
            class: App\Producer\SumValuesProducer
            connection:       default
            exchange_options: {name: 'sum_values', type: direct}
            #service_alias:    my_app_service # no alias by default
    consumers:
        sum_values:
            connection:       default
            exchange_options: {name: 'sum_values', type: direct}
            queue_options:    {name: 'sum_values'}
            callback:         App\Consumer\SumValuesConsumer