version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    working_dir: /app
    user: application
    restart: always
    volumes:
      - .:/app:delegated
      - ~/.composer:/home/application/.composer:delegated
      - ~/.node_modules:/home/application/.node_modules:delegated
      - ~/.ssh:/home/application/.ssh:ro
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      WEB_DOCUMENT_INDEX: "index.php"
      PHP_DATE_TIMEZONE: "UTC"
      COMPOSER_MEMORY_LIMIT: "-1"
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_testAmqp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - db:/var/lib/mysql
      - ./dumps:/shared
    ports:
      - 31306:3306

volumes:
  db: ~
